# Generated by Django 2.0.6 on 2018-07-06 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileChunk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_sha256', models.CharField(max_length=64)),
                ('chunk_id', models.IntegerField()),
                ('chunk_startByte', models.IntegerField()),
                ('chunk_endByte', models.IntegerField()),
                ('file_sha256', models.CharField(max_length=64)),
                ('file_lastModifiedDate', models.DateTimeField()),
                ('file_name', models.CharField(max_length=256)),
                ('file_size', models.IntegerField()),
                ('data', models.BinaryField()),
            ],
        ),
    ]
