name: BigScience

channels:
  - conda-forge

dependencies:
  - python=3.6.5
  - django=2.0.6
  - djangorestframework=3.8.2
  - pyjwt=1.6.4
  - libhdfs3=2.3
  - hdfs3=0.3.0
  - redis-py=2.10.6
  - python-dateutil=2.7
  - celery[redis]=4.1.1
  - pip:
    - djongo==1.2.23
    - django-cors-headers==2.2.0
    - django-nose==1.4.5
    - coverage==4.5.1
