name: BigScience

channels:
  - conda-forge

dependencies:
  - python=3.6.5
  - pyjwt=1.6.4
  - libhdfs3=2.3
  - hdfs3=0.3.0
  - redis-py=2.10.6
  - python-dateutil=2.7
  - celery[redis]=4.1.1
  - pip:
    - pymongo==3.7.1
    - bcrypt==3.1.4
    - coverage==4.5.1
    - sanic==0.7.0
    - sanic-cors==0.9.4
    - sanic-openapi==0.4.0
    - AoikLiveReload==0.1.0
