name: BigScience

channels:
  - conda-forge

dependencies:
  - python=3.6.5
  - django=2.0.6
  - djangorestframework=3.8.2
  - pyjwt=1.6.4
  - libhdfs3
  - hdfs3
  - pip:
    - djongo==1.2.23
    - djangorestframework-jwt==1.11.0
    - django-cors-headers==2.2.0
    - django-nose==1.4.5
    - coverage==4.5.1
